### ISSUE TITLE
Need to add CPU and memory affinity

### ISSUE THREAD

**Issue by whnbaek** [sunhongmin225/dgx-a100-server-allocation#1]
```
--cpuset-cpus string             CPUs in which to allow execution (0-3, 0,1)
--cpuset-mems string             MEMs in which to allow execution (0-3, 0,1)
```

**Comment by whnbaek** [comment]
For example, if GPU is 3,4 and
```
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-255
```
--cpuset-cpus 48-63,176-191,64-79,192-207
--cpuset-mems 3,4

**Comment by whnbaek** [comment]
선택지에서 CPU 개수나 메모리 용량도 받도록 하면 많이 복잡할 듯합니다. NUMA 구조이기도 해서 그냥 이 두개는 지우고
사용할 GPU의 개수, Disk의 용량, OS 종류, CUDA toolkit 버전, cuDNN 버전 이렇게만 받아서 생성해주는 건 어떨까요?
여러 GPU 배정 시에도
![image](https://user-images.githubusercontent.com/10656858/169163273-5722dd08-14a8-476c-a195-310983bc7f01.png)
이 구조에 따라 가까운 GPU들끼리 잘 배분해야할 듯합니다.

**Comment by sunhongmin225** [comment]
그런데 걱정인게 CPU개수나 메모리 용량을 제한해놓지 않으면 누군가는 과도하게 많이 사용할 것 같은데 그런 문제는 handle하기 어렵지 않을까요?

**Comment by whnbaek** [comment]
아 제 말은 GPU당 메모리 128GB, CPU 32개로 그냥 고정하자는 의미였습니다.
host가 쓸 메모리까지 포함해서 메모리는 GPU당 한 120GB?

**Comment by sunhongmin225** [comment]
아하 그렇군요 수요가 어떻게 될지 가늠하기 어려워서 이 부분은 이따 교수님께 의견 여쭤보기로하죠

**Comment by sunhongmin225** [comment]
> For example, if GPU is 3,4 and
> 
> ```
> NUMA node0 CPU(s):               0-15,128-143
> NUMA node1 CPU(s):               16-31,144-159
> NUMA node2 CPU(s):               32-47,160-175
> NUMA node3 CPU(s):               48-63,176-191
> NUMA node4 CPU(s):               64-79,192-207
> NUMA node5 CPU(s):               80-95,208-223
> NUMA node6 CPU(s):               96-111,224-239
> NUMA node7 CPU(s):               112-127,240-255
> ```
> 
> --cpuset-cpus 48-63,176-191,64-79,192-207 --cpuset-mems 3,4

여기서 `--cpuset-mems 3,4` 이런 식으로 주면 메모리 얼마를 주는건가요?

**Comment by whnbaek** [comment]
사실 저 affinity만 주더라도 특정 메모리만 사용하게 강제하므로 우리 서버 세팅에 따르면 약 256기가 정도로 제한될 겁니다. 이거 말고 memory 용량 정해주는 건 그냥 cgroup으로 소프트웨어적으로 상한을 정해주는 거 같습니다.

**Comment by sunhongmin225** [comment]
제안하신대로 GPU당 메모리 (128GB), CPU (32개) 고정하는걸로 수정했습니다.
