### ISSUE TITLE
reboot 시 mount 해제 및 docker 재설정 문제

### ISSUE THREAD

**Issue by whnbaek** [sunhongmin225/dgx-a100-server-allocation#2]
reboot 하게 되면 /raid로의 mount가 해제되고 docker가 start 된 상태로 시작해서 /var/lib/docker -> /raid/docker이 해제되고 그 자리에 새로운 docker 파일들이 설정됩니다.
sudo mount /dev/md1 /raid
sudo systemctl stop docker
sudo rm -rf /var/lib/docker
sudo mkdir /var/lib/docker
sudo mount --rbind /raid/docker /var/lib/docker
해주면 되지만
매번 이렇게 하는 게 번거로울 거 같습니다.
재시작 시 mount /dev/md1 /raid를 자동으로 되도록 설정하는 방법에 대한 안내가 필요할 듯합니다.

**Comment by sunhongmin225** [comment]
네 그러면 말씀하신 내용을 담아서 `crontab -e`로 reboot 시마다 script 를 자동으로 실행하게끔 추가하면 어떨까요?

**Comment by sunhongmin225** [comment]
설명 추가했습니다.
